import Head from 'next/head'
import Image from 'next/image'
import Nav from '../Nav'
import Footer from '../Footer'
import styles from './Styles.module.scss'

export default function Layout({ children, title }) {
  return (
    <>
        <Head>
            <title>{title? `${title} | `: null} Web Strategy, Web Development, Startups | Seattle</title>
            <meta name="Shaun Yap | Web Strategy x Web Development, Startup" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <style>
            @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Ruthie&display=swap');
            </style>
        </Head>
      <Nav />
      <div className={styles.wrapper}>
        <main>
            <div className={styles.logo}>
                <div className={styles.img_container} ><Image src="/logo_square.jpg" alt="Logo of a triangle with an enclosed circle" width="50" height="50"/></div>
            </div>
            {children}
        </main>
      </div>
      <Footer />
    </>
  )
}