import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import fs from 'fs'
const path = require('path')
import matter from 'gray-matter'

import styles from './Home.module.scss'
import Nav from '../components/Nav'
import Footer from '../components/Footer'


export async function getStaticProps() {
  const getPostsForIndex = (directory, numberOfPosts) => {
    
    const fileMeta = (fileName) => {
      const fileContents = fs.readFileSync(path.resolve(`./src/${directory}/${fileName}`,'./index.md'), 'utf8')
      const { data } = matter(fileContents)
      const {title, date} = data

      return {
        path: `/${directory}/${fileName}`,
        title,
        date
      }
    }

    const posts = []
    const fileNames = fs.readdirSync(`./src/${directory}`);
    fileNames.map(fileName => {
      posts.push(fileMeta(fileName))
    })

    posts.sort((a,b) => a.date - b.date);
    return posts.slice(0, numberOfPosts)
  }

  const projects = await getPostsForIndex('projects');
  const blogPosts = await getPostsForIndex('blog');

  return {
    props: {
      projects,
      blogPosts
    }
  }
}


export default function Home(props) {
  return (
    <div className="wrapper">
      <Head>
        <title>Web Marketing, Web Development, Startups | Seattle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Ruthie&display=swap');
        </style>
      </Head>

      <Nav />
      <main className={styles.main}>
        <section>
          <article className={styles.article}>
            <h1 className={styles.title}>
              Seattle-based web developer and marketer
            </h1>
            <div className={styles.social_media}>
              <div>
                <Link href="https://github.com/shaunyap"><a><Image src='/github.svg' alt="Github logo" width={20} height={20}/></a></Link>
                <Link href="https://linkedin.com/in/shauny"><a><Image src='/linkedin.svg' alt="LinkedIn logo" width={20} height={20}/></a></Link>
                <Link href="https://www.instagram.com/shaunyap"><a><Image src='/instagram.svg' alt="Instagram logo" width={20} height={20}/></a></Link>
              </div>
            </div>
            <div>
            <p>Hello there, thanks for dropping by! I&#8217;m Shaun. My day job is building and managing <a href="https://amperity.com">Amperity&#8217;s web properties</a> to drive business results for the organization.</p>

            <p>Previously, I led the web strategy for <a href="https://chef.io">Chef Software</a> which was acquired by Progress Software for US$220m. I&#8217;ve also done some award-winning work at <a href="https://www.campaignlive.com/article/wpp-unveils-wavemaker-name-merged-mec-maxus-agency/1443769">the agency formerly known as MEC</a> in Singapore as well as in Dubai.</p>

            <p>Feel free to <a href="mailto:shaun@siegeflow.com">say hi</a> if you want to chat about web dev, and how it can to drive organizational value.</p>
       
              <p className={styles.signoff}>shaunyap</p>
            </div>
            <hr />
          </article>
        </section>
        <section className={styles.half}>
          <div>
          <h2>Selected past work</h2>
          <ul className="post_index">
            {props.projects.map(post => (
              <Link href={post.path} key={post.path}><a><li>{post.title}</li></a></Link>
            )) }
          </ul>
          </div>
          <div>
          <h2>Blog posts</h2>
          <ul className="post_index">
            {props.blogPosts.map(post => (
              <Link href={post.path} key={post.path}><a><li>{post.title}</li></a></Link>
            )) }
          </ul>
          </div>
        </section>

      </main>
      <Footer />
    </div>
  )
}
