import Head from 'next/head'
import Image from 'next/image'
import styles from './Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shaun Yap, Technical Marketing Leader | Seattle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <article>
          <h1 className={styles.title} >
            Hello World!
          </h1>
          <div className="copyContainer">
            <p>I'm Shaun, a front-end developer and marketer in Seattle currently leading the web team at <a href="https://amperity.com">Amperity</a>.</p>
            <p>Previously, I ran the web strategy for <a href="https://www.chef.io">Chef Software</a>, freelanced as a web development and marketing strategy consultant, and I also did some <a href="https://www.caltex.com/sg/about-us/news/2012/driving-change-with-caltex-community-project-raises-105420-this-past-weekend-for-needy-elderly-nationwide.html">award-winning work</a> at the <a href="https://wavemakerglobal.com/">agency formerly known as MEC</a> in Asia as well as the Middle East.</p>  
              
            <p className="signOff">- shaunyap</p>
          </div>
        </article>
        <aside>
          <h2>Selected Past Work</h2>
          <ul>
            <li>Amperity.com Replatform</li>
            <li>Amperity.com Replatform</li>
            <li>Amperity.com Replatform</li>
          </ul>
        </aside>
        <aside>
          <h2>Blog posts</h2>
        </aside>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
